<?php
declare(strict_types=1);

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ConfigParser extends Command
{
    protected static $defaultName = 'app:parser-files';

    protected static $defaultDescription = 'Environment config parser';

    /**
     * @inheritDoc
     */
    public function __construct(string $name = null)
    {
        parent::__construct($name);
    }

    /**
     * @inheritDoc
     */
    public function execute(InputInterface $input, OutputInterface $output): int
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub

        return Command::SUCCESS;
    }
}